---
variables:
  CONTAINER_TEST: registry.gitlab.com/collegiumv/docker-papercut

stages:
  - docker-build

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $CONTAINER_TEST .
